### ISSUE TITLE
打样出错

### ISSUE THREAD

**Issue by Eleven-JL** [zhangbokang/PCB_Fixture#1]
![Screenshot_2024-11-06-00-46-30-83_e39d2c7de19156b0683cd93e8735f348](https://github.com/user-attachments/assets/0b7ca361-8347-443d-9bd3-8a89e3d7679e)

**Comment by zhangbokang** [comment]
我打的时候没提示，可能是检测差异导致的，用新版本的吧，新版本的没有这个问题了
